name: ServerCommands
version: 1.0
author: EvisPresley
main: me.TKUIYEAGER1.ServerPrefix.Main
description: Changes The Server's prefix
commands:
    server:
        description: Shows The Server Prefix
        Created By:EvisPresley
